# Generated by Django 2.1.1 on 2019-06-05 05:22

import df_goods.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='gpic',
            field=models.ImageField(blank=True, null=True, storage=df_goods.storage.ImageStorage(), upload_to='article_img/%Y%m', verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='gunit',
            field=models.CharField(default='500g', max_length=20, verbose_name='规格'),
        ),
    ]
